# Generated by Django 3.0.8 on 2020-07-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('تالیفی', 'info'), ('ترجمه ای', 'success'), ('کاربران', 'warning')], default='info', max_length=20)),
            ],
        ),
    ]
